"use server"

import { redirect } from "next/navigation"
import { z } from "zod"
import { requireUser } from "@/lib/auth/guard"
import { createClient } from "@/lib/supabase/server"
import type { TablesInsert } from "@/types"

// ── Zod schemas ───────────────────────────────────────────────────────────────

const StopSchema = z.object({
  placeId: z.string(),
  name:    z.string().min(1),
  address: z.string(),
  lat:     z.number(),
  lng:     z.number(),
})

const QuestionSchema = z.object({
  text:    z.string().min(1, "Question text is required").max(200),
  type:    z.enum(["single", "multiple"]),
  options: z.array(z.string().min(1).max(120)).min(2).max(8),
})

export const CreateEventSchema = z.object({
  title:           z.string().trim().min(1, "Title is required").max(120),
  description:     z.string().trim().max(500).optional(),
  // datetime-local string "YYYY-MM-DDTHH:mm" — stored as UTC (GMT/BST parity on server)
  date:            z.string().optional(),
  type:            z.enum(["night_out", "lunch", "coffee", "team_building", "activity", "other"]),
  alcoholFriendly: z.boolean(),
  pollQuestions:   z.array(QuestionSchema).max(10),
  stops:           z.array(StopSchema).max(20),
})

export type CreateEventInput = z.infer<typeof CreateEventSchema>

// ── Action ────────────────────────────────────────────────────────────────────

export async function createEvent(
  rawInput: CreateEventInput
): Promise<{ error: string } | void> {
  const user = await requireUser()

  // Strip blank questions / options before schema validation (polls are optional)
  const sanitised: CreateEventInput = {
    ...rawInput,
    pollQuestions: rawInput.pollQuestions
      .map((q) => ({ ...q, options: q.options.filter((o) => o.trim()) }))
      .filter((q) => q.text.trim() && q.options.length >= 2),
  }

  const parsed = CreateEventSchema.safeParse(sanitised)
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" }
  }

  const data   = parsed.data
  const supabase = await createClient()

  // ── 1. Insert event (share_token auto-generated by DB default) ────────────

  const eventRow: TablesInsert<"events"> = {
    organiser_id:    user.id,
    title:           data.title,
    description:     data.description || null,
    type:            data.type,
    // Treat datetime-local value as UTC; TODO: convert from UK local time once
    // the client passes an explicit offset (BST = UTC+1, GMT = UTC+0).
    date:            data.date ? `${data.date}:00+00:00` : null,
    alcohol_friendly: data.alcoholFriendly,
  }

  const { data: event, error: eventErr } = await supabase
    .from("events")
    .insert(eventRow)
    .select("id")
    .single()

  if (eventErr || !event) {
    return { error: eventErr?.message ?? "Failed to create event" }
  }

  const { id: eventId } = event

  // ── 2. Poll questions + options ───────────────────────────────────────────

  for (const q of data.pollQuestions) {
    const questionRow: TablesInsert<"poll_questions"> = {
      event_id:      eventId,
      question_text: q.text,
      // DB question_type categorises the topic (venue/date/activity/other).
      // The form's answer-type (single/multiple) is a voting-UI concern stored
      // client-side only; both map to "other" for now.
      question_type: "other",
    }

    const { data: question, error: qErr } = await supabase
      .from("poll_questions")
      .insert(questionRow)
      .select("id")
      .single()

    if (qErr || !question) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: qErr?.message ?? "Failed to create poll question" }
    }

    const optionRows: TablesInsert<"poll_options">[] = q.options.map((text) => ({
      question_id: question.id,
      option_text: text,
    }))

    const { error: optErr } = await supabase.from("poll_options").insert(optionRows)

    if (optErr) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: optErr.message }
    }
  }

  // ── 3. Map stops ──────────────────────────────────────────────────────────

  if (data.stops.length > 0) {
    const stopRows: TablesInsert<"event_stops">[] = data.stops.map((s, i) => ({
      event_id: eventId,
      place_id: s.placeId || null,
      name:     s.name,
      address:  s.address,
      lat:      s.lat,
      lng:      s.lng,
      order:    i,
    }))

    const { error: stopsErr } = await supabase.from("event_stops").insert(stopRows)

    if (stopsErr) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: stopsErr.message }
    }
  }

  // ── 4. Redirect to new event page ─────────────────────────────────────────

  redirect(`/events/${eventId}?created=1`)
}
