"use server"

import { redirect } from "next/navigation"
import { revalidatePath } from "next/cache"
import { z } from "zod"
import { requireUser } from "@/lib/auth/guard"
import { createClient } from "@/lib/supabase/server"
import type { TablesInsert } from "@/types"

// ── Zod schemas ───────────────────────────────────────────────────────────────

const StopSchema = z.object({
  placeId: z.string(),
  name:    z.string().min(1),
  address: z.string(),
  lat:     z.number(),
  lng:     z.number(),
})

const QuestionSchema = z.object({
  text:    z.string().min(1, "Question text is required").max(200),
  type:    z.enum(["single", "multiple"]),
  options: z.array(z.string().min(1).max(120)).min(2).max(8),
})

export const CreateEventSchema = z.object({
  title:           z.string().trim().min(1, "Title is required").max(120),
  description:     z.string().trim().max(500).optional(),
  // datetime-local string "YYYY-MM-DDTHH:mm" — stored as UTC (GMT/BST parity on server)
  date:            z.string().optional(),
  type:            z.enum(["night_out", "lunch", "coffee", "team_building", "activity", "other"]),
  alcoholFriendly: z.boolean(),
  pollQuestions:   z.array(QuestionSchema).max(10),
  stops:           z.array(StopSchema).max(20),
})

export type CreateEventInput = z.infer<typeof CreateEventSchema>

// ── Action ────────────────────────────────────────────────────────────────────

export async function createEvent(
  rawInput: CreateEventInput
): Promise<{ error: string } | void> {
  const user = await requireUser()

  // Strip blank questions / options before schema validation (polls are optional)
  const sanitised: CreateEventInput = {
    ...rawInput,
    pollQuestions: rawInput.pollQuestions
      .map((q) => ({ ...q, options: q.options.filter((o) => o.trim()) }))
      .filter((q) => q.text.trim() && q.options.length >= 2),
  }

  const parsed = CreateEventSchema.safeParse(sanitised)
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" }
  }

  const data   = parsed.data
  const supabase = await createClient()

  // ── 1. Insert event (share_token auto-generated by DB default) ────────────

  const eventRow: TablesInsert<"events"> = {
    organiser_id:    user.id,
    title:           data.title,
    description:     data.description || null,
    type:            data.type,
    // Treat datetime-local value as UTC; TODO: convert from UK local time once
    // the client passes an explicit offset (BST = UTC+1, GMT = UTC+0).
    date:            data.date ? `${data.date}:00+00:00` : null,
    alcohol_friendly: data.alcoholFriendly,
  }

  const { data: event, error: eventErr } = await supabase
    .from("events")
    .insert(eventRow)
    .select("id")
    .single()

  if (eventErr || !event) {
    return { error: eventErr?.message ?? "Failed to create event" }
  }

  const { id: eventId } = event

  // ── 2. Poll questions + options ───────────────────────────────────────────

  for (const q of data.pollQuestions) {
    const questionRow: TablesInsert<"poll_questions"> = {
      event_id:      eventId,
      question_text: q.text,
      // DB question_type categorises the topic (venue/date/activity/other).
      // The form's answer-type (single/multiple) is a voting-UI concern stored
      // client-side only; both map to "other" for now.
      question_type: "other",
    }

    const { data: question, error: qErr } = await supabase
      .from("poll_questions")
      .insert(questionRow)
      .select("id")
      .single()

    if (qErr || !question) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: qErr?.message ?? "Failed to create poll question" }
    }

    const optionRows: TablesInsert<"poll_options">[] = q.options.map((text) => ({
      question_id: question.id,
      option_text: text,
    }))

    const { error: optErr } = await supabase.from("poll_options").insert(optionRows)

    if (optErr) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: optErr.message }
    }
  }

  // ── 3. Map stops ──────────────────────────────────────────────────────────

  if (data.stops.length > 0) {
    const stopRows: TablesInsert<"event_stops">[] = data.stops.map((s, i) => ({
      event_id: eventId,
      place_id: s.placeId || null,
      name:     s.name,
      address:  s.address,
      lat:      s.lat,
      lng:      s.lng,
      order:    i,
    }))

    const { error: stopsErr } = await supabase.from("event_stops").insert(stopRows)

    if (stopsErr) {
      await supabase.from("events").delete().eq("id", eventId)
      return { error: stopsErr.message }
    }
  }

  // ── 4. Redirect to new event page ─────────────────────────────────────────

  redirect(`/events/${eventId}?created=1`)
}

// ── castVote ──────────────────────────────────────────────────────────────────
// Upsert a poll vote: delete any existing vote for this question, then insert.
// DB has no UPDATE policy on poll_votes (unique constraint: user + question).

export async function castVote(
  optionId:   string,
  questionId: string,
): Promise<{ error: string } | void> {
  const user     = await requireUser()
  const supabase = await createClient()

  // Delete existing vote for this question (no-op if not yet voted)
  const { error: delErr } = await supabase
    .from("poll_votes")
    .delete()
    .eq("user_id",     user.id)
    .eq("question_id", questionId)

  if (delErr) return { error: delErr.message }

  const { error: insErr } = await supabase
    .from("poll_votes")
    .insert({ option_id: optionId, question_id: questionId, user_id: user.id })

  if (insErr) return { error: insErr.message }
}

// ── upsertRsvp ────────────────────────────────────────────────────────────────

const RsvpSchema = z.object({
  eventId:            z.string().uuid(),
  status:             z.enum(["yes", "no", "maybe"]),
  drinkingPreference: z.enum(["yes", "no", "maybe"]),
})

export async function upsertRsvp(
  input: z.infer<typeof RsvpSchema>
): Promise<{ error: string } | void> {
  const parsed = RsvpSchema.safeParse(input)
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid input" }

  const user     = await requireUser()
  const supabase = await createClient()

  const { error } = await supabase
    .from("rsvps")
    .upsert(
      {
        event_id:            parsed.data.eventId,
        user_id:             user.id,
        status:              parsed.data.status,
        drinking_preference: parsed.data.drinkingPreference,
      },
      { onConflict: "user_id, event_id" }
    )

  if (error) return { error: error.message }

  redirect(`/events/${parsed.data.eventId}`)
}

// ── deleteEventStop ───────────────────────────────────────────────────────────

export async function deleteEventStop(
  stopId:  string,
  eventId: string,
): Promise<{ error: string } | void> {
  await requireUser()
  const supabase = await createClient()

  const { error } = await supabase
    .from("event_stops")
    .delete()
    .eq("id", stopId)
    .eq("event_id", eventId) // RLS guard via policy; belt-and-braces filter

  if (error) return { error: error.message }
  revalidatePath(`/events/${eventId}`)
}

// ── reorderEventStops ─────────────────────────────────────────────────────────
// Receives the full ordered array of stop IDs and writes each stop's new index.

export async function reorderEventStops(
  eventId:    string,
  orderedIds: string[],
): Promise<{ error: string } | void> {
  await requireUser()
  const supabase = await createClient()

  const updates = orderedIds.map((id, index) =>
    supabase
      .from("event_stops")
      .update({ order: index })
      .eq("id", id)
      .eq("event_id", eventId)
  )

  const results = await Promise.all(updates)
  const failed  = results.find((r) => r.error)
  if (failed?.error) return { error: failed.error.message }

  revalidatePath(`/events/${eventId}`)
}

// ── uploadMemory ──────────────────────────────────────────────────────────────

const ALLOWED_MIMES = [
  "image/jpeg", "image/png", "image/webp", "image/gif",
  "video/mp4", "video/quicktime", "video/webm",
] as const

const MAX_FILE_BYTES = 50 * 1024 * 1024 // 50 MB

const UploadSchema = z.object({
  eventId:  z.string().uuid("Invalid event ID"),
  caption:  z.string().max(140, "Caption must be 140 characters or fewer"),
  fileType: z
    .string()
    .refine((t): t is typeof ALLOWED_MIMES[number] => ALLOWED_MIMES.includes(t as never), {
      message: "Unsupported file type — use JPG, PNG, WEBP, GIF, MP4, MOV, or WEBM",
    }),
  fileSize: z.number().max(MAX_FILE_BYTES, "File must be smaller than 50 MB"),
})

function sanitizeFilename(name: string): string {
  const ext  = name.split(".").pop()?.toLowerCase() ?? "bin"
  const base = name
    .replace(/\.[^.]+$/, "")        // strip extension
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")    // only safe chars
    .replace(/-+/g, "-")            // collapse consecutive dashes
    .slice(0, 80)                   // cap length
  return `${base || "file"}.${ext}`
}

export async function uploadMemory(
  formData: FormData,
): Promise<{ error: string } | void> {
  const file    = formData.get("file")
  const eventId = formData.get("eventId")
  const caption = formData.get("caption")

  if (!(file instanceof File))      return { error: "No file provided" }
  if (typeof eventId !== "string")  return { error: "Missing event ID" }

  const parsed = UploadSchema.safeParse({
    eventId:  eventId.trim(),
    caption:  typeof caption === "string" ? caption.trim() : "",
    fileType: file.type,
    fileSize: file.size,
  })
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid input" }

  const user     = await requireUser()
  const supabase = await createClient()

  // Storage path: events/<eventId>/<timestamp>-<safe-filename>
  const safeName    = sanitizeFilename(file.name)
  const storagePath = `events/${parsed.data.eventId}/${Date.now()}-${safeName}`

  const { error: uploadErr } = await supabase.storage
    .from("memories")
    .upload(storagePath, file, { contentType: file.type, upsert: false })

  if (uploadErr) return { error: uploadErr.message }

  const mediaType: "image" | "video" = file.type.startsWith("video/") ? "video" : "image"

  const { error: insertErr } = await supabase.from("memories").insert({
    event_id:     parsed.data.eventId,
    uploader_id:  user.id,
    storage_path: storagePath,
    media_type:   mediaType,
    caption:      parsed.data.caption || null,
  })

  if (insertErr) {
    // Roll back the storage upload if the DB insert fails
    await supabase.storage.from("memories").remove([storagePath])
    return { error: insertErr.message }
  }

  revalidatePath(`/events/${parsed.data.eventId}`)
  revalidatePath(`/events/${parsed.data.eventId}/memory-box`)
}
